task :default => [ :starttunel ]

desc 'Starts tunnel with the server machine'
task :starttunnel do
 sh %{ssh -L61675:localhost:61676 -N pp2 &} 
end

desc 'Starts server'
task :startserver do
 # assume there is a link 'DrbSSH' to the work dir
 # assume ruby1.9.2
 sh "ssh pp2 'ruby ~/DrbSSH/helloworldserver.rb' &"
end

desc 'Starts client'
task :startclient do
 sh "ruby helloworldclient.rb"
end

desc "Kills the server and the producer"
task :clean do
  puts %x{
    pkill -s 9 -f 'ssh -L61675:localhost:61676 -N pp2' | grep -v pgrep
  }
  puts %x{
    ssh pp2 'pkill -s 9 -f "ruby ./DrbSSH/helloworldserver.rb"' 
  }
  puts %x{
    pkill -s 9 -f 'ssh pp2 ruby ./DrbSSH/helloworldserver.rb' 
  }
end

desc "Show the process matching 'ruby'"
task :show do
  puts %x{
    pgrep -f -l 'ssh -L61675:localhost:61676 -N pp2' | grep -v pgrep
  }
  puts "Remote:"
  puts %x{
    ssh pp2 'pgrep -l -f "ruby ./DrbSSH/helloworldserver.rb"'
  }
  puts %x{
    pgrep -f -l 'ssh pp2 ruby ./DrbSSH/helloworldserver.rb' | grep -v pgrep
  }
end
