# From the book "Distributed Programming with Ruby"
task :default => [ :startclient ]

desc 'Starts server'
task :startserver do
 sh %{ruby helloworldserver.rb} unless File.readable? 'DRbhw.proc'
end

desc 'Starts server in a new XTERM'
task :startserverX do
 sh %{xterm -e 'ruby helloworldserver.rb' &} unless File.readable? 'DRbhw.proc'
end

desc 'Starts SAFE server'
task :startsafeserver do
 sh %{xterm -e 'ruby safehelloworldserver.rb' &} unless File.readable? 'DRbhw.proc'
end

desc 'Starts client'
task :startclient do
 sh "ruby helloworldclient.rb"
end

desc 'Starts BAD client with unsafe server'
task :startbadclient do
 sh <<"EOBCL"
 ruby helloworldbadclient.rb
 ls -l CHUCHUM
 cat -n CHUCHUM
EOBCL
end

desc 'Starts BAD client with SAFE server'
task :startbadclientwithsafe do
 sh <<"EOBCL"
 ruby helloworldbadclient.rb
 ls -l CHUCHUM
 cat -n CHUCHUM
EOBCL
end

desc "Kill the server"
task :clean do
  if File.readable? 'DRbhw.proc'
    process = File.open('DRbhw.proc').gets.chomp!.to_i
    Process.kill(9, process) if Process.kill(0, process)
    File.delete('DRbhw.proc')
    File.delete('CHUCHUMMMM') if  File.readable? 'CHUCHUMMMM'
  end
  File.delete('CHUCHUM') if  File.readable? 'CHUCHUM'
end

desc "Show the proceses matching 'ruby' and the env vars matching 'ssh'"
task :show do
  sh %{ps -fA | grep 'ruby' | grep -v $$}
  sh %{env | grep -i ssh}
end
