# From the book "Distributed Programming with Ruby"
task :default => [ :startclient ]

desc 'Builds the SSL certificates'
task :certificates => [ 'qc_config' ] do
  unless File.readable? 'hello-client'
    sh "rm -fR CA hello-client hello-server"
    sh "QuickCert"
    sh "tree"
  end
end

desc 'Starts server'
task :startserver => :certificates do
 sh %{ruby helloworldserver.rb} unless File.readable? 'DRbhw.proc'
end

desc 'Starts server in a new XTERM'
task :startserverX => :certificates do
 sh %{xterm -e 'ruby helloworldserver.rb' &} unless File.readable? 'DRbhw.proc'
end

desc 'Starts client'
task :startclient do
 sh "ruby helloworldclient.rb"
end

desc 'Starts simple client'
task :startsimpleclient do
 sh <<"EOBCL"
 ruby helloworldsimpleclient.rb
EOBCL
end

desc 'Starts server with Authorization'
task :startsafeserver => :certificates do
 sh %{ruby safehelloworldserver.rb} 
end

desc 'Starts safe client'
task :startsafeclient do
 sh "ruby safehelloworldclient.rb"
end

desc "Kill the server"
task :clean do
  if File.readable? 'DRbhw.proc'
    begin
      process = File.open('DRbhw.proc').gets.chomp.to_i
      Process.kill(9, process) 
    rescue
    ensure
      File.delete('DRbhw.proc')
      File.delete('CHUCHUMMMM') if  File.readable? 'CHUCHUMMMM'
    end
  end
  File.delete('CHUCHUM') if  File.readable? 'CHUCHUM'
  sh "rm -fR CA hello-client hello-server"
end

desc "Show the proceses matching 'ruby' and the env vars matching 'ssh'"
task :show do
  sh %{ps -fA | grep 'ruby' | grep -v $$}
  sh %{env | grep -i ssh}
end
