program = 'hello_chat'

desc "Compile #{program}.opa"
task :default => :compile
task :compile => program+".opa" do
 sh %Q{opa --parser js-like #{program}.opa}
end

task :run => "#{program}.exe" do
  sh "./#{program}.exe"
end

require 'rake/clean'
CLEANLIST = [ "#{program}.exe", "_build", "*.log", "*.error" ]
CLEAN.include(CLEANLIST)

