require 'rubygems'

spec = Gem::Specification.new do |s|
  s.platform = Gem::Platform::RUBY
  s.summary = "Makes anagrams of a word."
  s.name = 'anagram'
  s.version = '0.0.1' # PKG_VERSION
  s.requirements << 'none'
  s.require_path = 'lib'
  #s.autorequire = 'rake'
  s.files = Dir['**/**'] # PKG_FILES
  s.description = <<-EOF
anagram is an executable that gives you the anagrams
of a given word
EOF
end

Rake::GemPackageTask.new(spec) do |pkg|
  pkg.need_zip = true
  pkg.need_tar = true
end

require 'rake/testtask'

# rake test TEST=just_one_file.rb     # run just one test file.
# rake test TESTOPTS="-v"             # run in verbose mode
Rake::TestTask.new do |t|
  # t.libs: List of directories to be added to $LOAD_PATH. (default is ‘lib’)
  t.libs << "test" 
  t.pattern = 'test/tc*.rb' # or t.test_files = FileList['test/tc*.rb'] 
  t.warning = true
  t.verbose = true # verbose test output. (default is false)
end
