task :default => [ :startclient ]

desc 'Starts server'
task :startserver do
 sh %{xterm -e 'ruby idconvserver.rb' &} unless File.readable? 'DRbhw.proc'
end

desc 'Starts client'
task :startclient => :startserver do
 sh "ruby idconvclient.rb"
end

desc 'Starts server with customized ID Converter'
task :startcustomserver do
 sh %{xterm -e 'ruby customidserver.rb' &} unless File.readable? 'DRbhw.proc'
end

desc "Kill the server"
task :clean do
  if File.readable? 'DRbhw.proc'
    process = File.open('DRbhw.proc').gets.chomp!.to_i
    Process.kill(9, process) if Process.kill(0, process)
    File.delete('Drbhw.proc')
  end
end

desc "Show the process matching 'ruby'"
task :show do
  sh %{ps -fA | grep 'ruby' | grep -v $$}
end
