require 'rubygems'
require 'rubygems/package_task'

spec = Gem::Specification.new do |s|
  s.platform = Gem::Platform::RUBY
  s.summary = "Ruby based make-like utility."
  s.name = 'pipelineelement'
  s.version = "0.1.1"
  s.requirements << 'none'
  s.require_path = 'lib'
  #s.autorequire = 'pipelineelement'
  #s.files = PKG_FILES
  s.authors = ['Casiano']
  s.files = Dir['**/**']
  s.homepage = "http://puchurrum.com"
  s.email = "casiano@pum.uk"
  s.description = "PipelineElement and dependencies are specified in standard Ruby syntax.  "
end

Gem::PackageTask.new(spec) do |pkg|
  pkg.need_zip = true
  pkg.need_tar = true
end
