#require "rubygems"
require "rake/packagetask"

Rake::PackageTask.new("hola_casiano", "0.0.1") do |p|
  p.need_tar = true
  p.need_zip = true

  p.package_files.include("lib/**/*.rb")
end
 

#Rake::GemPackageTask.new(spec) do |pkg|
#  pkg.need_zip = true
#  pkg.need_tar = true
#end
