program = 'hello'
source  = "#{program}.opa"
exe     = "#{program}.exe"

desc "Compile #{source}"
task :default => "#{exe}"

file "#{exe}" => program+".opa" do
 sh %Q{opa --parser js-like #{source}}
end

desc "Starts the server"
task :start => "#{exe}" do
  sh "./#{exe}"
end

require 'rake/clean'
CLEANLIST = [ "#{exe}", "_build", "*.log", "*.error" ]
CLEAN.include(CLEANLIST)

#task :clean do
#  sh "rm -fR #{MAINNAME}/"
#end

